### ISSUE TITLE
Проблема с экранирование на windows

### ISSUE THREAD

**Issue by ghost** [enb-bem/enb-bh-php#5]
Настоящий путь
`D:\Projects\fun.melmac\.view\desktop.bundles\top-pvp\top-pvp.bh.php`

По выполнению происходят проблемы с `\t` или `\f` и на выходе в `.html` получается это:

```
php process exited with code 255\n,PHP Warning:  require(D:\Projectsun.melmac\.view\desktop.bundles op-pvp  op-pvp.bh.php): failed to open stream: Invalid argument in - on line 11
PHP Fatal error:  require(): Failed opening required 'D:\Projectsun.melmac\.view\desktop.bundles    op-pvp  op-pvp.bh.php' (include_path='.;D:\PHP\pear') in - on line 11

Warning: require(D:\Projectsun.melmac\.view\desktop.bundles op-pvp  op-pvp.bh.php): failed to open stream: Invalid argument in - on line 11

Fatal error: require(): Failed opening required 'D:\Projectsun.melmac\.view\desktop.bundles op-pvp  op-pvp.bh.php' (include_path='.;D:\PHP\pear') in - on line 11
```

**Comment by qfox** [comment]
Ничосе. Я предполагал, что технология собрана из говна и палок, но удивительно, что только сейчас этот баг доехал ;-)

https://github.com/enb-bem/enb-bh-php/blob/master/techs/bemjson-to-html.js#L52 — вот на этой строке надо экранировать слеши, и проверить. Попробуешь? Если пришлешь PR — будет вообще замечательно

**Comment by qfox** [comment]
Попытался пофиксить в 0.1.5, если до сих пор не очень — напиши ;-)
